[package]
name = "fuzzyserve"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.9"
actix-web = "4.12.1"
clap = { version = "4.5.54", features = ["derive"] }
strsim = "0.11.1"
urlencoding = "2"
